name: Saltburn by the Sea
favicon: null
layout_spectrum: 0.3308271
typography_spectrum: 0.5602527
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#306AC0'
    - '#5A463B'
    - '#5DA6EB'
    - '#ADE7FF'
    - '#C99E74'
  brandStrength: 0
  lightness: 0.9419473
  saturation: 0.1648507
  rhythmicContrast: 0.2209275
purpose: []
