analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1648507
  brandStrength: 0
  rhythmicContrast: 0.2209275
  brandColors:
    - '#306AC0'
    - '#5A463B'
    - '#5DA6EB'
    - '#ADE7FF'
    - '#C99E74'
  lightness: 0.9419473
typography_spectrum: 0.5602527
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.02005013
favicon: null
name: Saltburn by the Sea
